name: ZAPPY GUI
run-name: ${{github.actor}} ZAPPY GUI
on:
  push:
    branches:
      - "**"

env:
  EXECUTABLE: "zappy_gui"
  WORKDIR: "App/GUI"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: epitechcontent/epitest-docker:latest

    steps:
      - uses: actions/checkout@v4

      - name: Check compilation
        run: |
          cd $WORKDIR
          mkdir ./build && cd ./build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .

      - name: Check binary
        run: |
          cd $WORKDIR
          if [[ ! -x "./${EXECUTABLE}" ]]; then
          echo "Error: Binary ${EXECUTABLE} not found."
          exit 1
          fi
